# Generated by Django 3.2 on 2023-07-27 12:30

import core.utils.make_document_directory_path
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import documents.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(150)])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('file', models.FileField(upload_to=core.utils.make_document_directory_path.make_documents_directory_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentpackage', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(related_name='DocumentDocumentPackage', to='documents.Document')),
            ],
            options={
                'verbose_name': 'Documents package',
                'verbose_name_plural': 'Documents packages',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='title')),
                ('name_in_document', models.CharField(help_text="name in document, prefer save add prefix '{{'and postfix '}}'", max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='template name in document')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='description')),
                ('is_official', models.BooleanField(blank=True, default=False, verbose_name='official tag')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TemplateValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=300)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templatevalue', to='documents.template')),
            ],
            options={
                'verbose_name': 'TemplateValue',
                'verbose_name_plural': 'TemplateValues',
            },
        ),
        migrations.CreateModel(
            name='UserDefaultTemplateValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdefaulttemplatevalue', to='documents.templatevalue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdefaulttemplatevalue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserDefaultTemplateValue',
                'verbose_name_plural': 'UserDefaultTemplateValues',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='documents.documentpackage')),
                ('templates_values', models.ManyToManyField(related_name='RecordTemplateValue', to='documents.TemplateValue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenttemplate', to='documents.document')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenttemplate', to='documents.template')),
            ],
            options={
                'verbose_name': 'DocumentTemplate',
                'verbose_name_plural': 'DocumentTemplates',
            },
        ),
        migrations.CreateModel(
            name='DocumentDocumentPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentdocumentpackage', to='documents.document')),
                ('document_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentdocumentpackage', to='documents.documentpackage')),
            ],
            options={
                'verbose_name': 'DocumentDocumentPackage',
                'verbose_name_plural': 'DocumentDocumentPackages',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='templates',
            field=models.ManyToManyField(related_name='DocumentTemplate', to='documents.Template'),
        ),
        migrations.AddConstraint(
            model_name='templatevalue',
            constraint=models.UniqueConstraint(fields=('template', 'value'), name='template_value_unique'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.UniqueConstraint(fields=('document', 'template'), name='document_template_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentdocumentpackage',
            constraint=models.UniqueConstraint(fields=('document', 'document_package'), name='document_document_package_unique'),
        ),
    ]
