# Generated by Django 3.2 on 2023-07-22 19:14

from django.db import migrations, models
import documents.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='title')),
                ('name_in_document', models.CharField(help_text="name in document, prefer save add prefix '{{'and postfix '}}'", max_length=30, unique=True, validators=[documents.validators.name_in_document_validator], verbose_name='template name in document')),
                ('description', models.TextField(max_length=500, unique=True, verbose_name='description')),
                ('is_official', models.BooleanField(blank=True, default=False, verbose_name='official tag')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['title'],
            },
        ),
    ]
