# Generated by Django 3.2 on 2023-07-27 14:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdocumentpackage',
            name='document_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentpackage'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.CreateModel(
            name='RecordTemplateValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.record')),
                ('template_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordtemplatevalue', to='documents.templatevalue')),
            ],
        ),
    ]
