# Generated by Django 3.2 on 2023-08-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_template_name_in_document'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentdocumentspackage',
            name='document_document_package_unique',
        ),
        migrations.RenameField(
            model_name='documentdocumentspackage',
            old_name='document_package',
            new_name='documents_package',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='document_package',
            new_name='documents_package',
        ),
        migrations.AlterField(
            model_name='documentdocumentspackage',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_packages', to='documents.document'),
        ),
        migrations.AddConstraint(
            model_name='documentdocumentspackage',
            constraint=models.UniqueConstraint(fields=('document', 'documents_package'), name='document_documents_package_unique'),
        ),
    ]
