# Generated by Django 3.2 on 2023-07-23 06:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20230722_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
