# Generated by Django 3.2 on 2023-07-23 06:44

import django.core.validators
from django.db import migrations, models
import documents.validators


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name_in_document',
            field=models.CharField(help_text="name in document, prefer save add prefix '{{'and postfix '}}'", max_length=30, unique=True, validators=[documents.validators.name_in_document_validator, django.core.validators.MinLengthValidator(7)], verbose_name='template name in document'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='title'),
        ),
    ]
