# Generated by Django 3.2 on 2023-07-28 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_auto_20230727_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpackage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdefaulttemplatevalue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_templates_values', to=settings.AUTH_USER_MODEL),
        ),
    ]
