# Generated by Django 3.2 on 2023-07-23 07:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_auto_20230723_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTemplateValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(1)])),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertemplatevalue', to='documents.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertemplatevalue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserTemplateValue',
                'verbose_name_plural': 'UserTemplateValues',
            },
        ),
        migrations.AddConstraint(
            model_name='usertemplatevalue',
            constraint=models.UniqueConstraint(fields=('user', 'template'), name='user_template_unique'),
        ),
    ]
