# Generated by Django 3.2 on 2023-08-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_record_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['-title'], 'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
    ]
