# Generated by Django 3.2 on 2023-07-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20230723_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemplatevalue',
            name='value',
            field=models.CharField(max_length=300),
        ),
    ]
