# Generated by Django 3.2 on 2023-07-23 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0006_alter_usertemplatevalue_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultUserTemplateValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=300)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaultusertemplatevalue', to='documents.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaultusertemplatevalue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserTemplateValue',
                'verbose_name_plural': 'UserTemplateValues',
            },
        ),
        migrations.DeleteModel(
            name='UserTemplateValue',
        ),
        migrations.AddConstraint(
            model_name='defaultusertemplatevalue',
            constraint=models.UniqueConstraint(fields=('user', 'template'), name='default_user_template_unique'),
        ),
    ]
