# Generated by Django 3.2 on 2023-07-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20230723_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultusertemplatevalue',
            options={'verbose_name': 'DefaultUserTemplateValue', 'verbose_name_plural': 'DeafaultUserTemplateValues'},
        ),
    ]
