# Generated by Django 3.2 on 2023-07-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_defaultusertemplatevalue_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, max_length=500, unique=True, verbose_name='description'),
        ),
    ]
