# Generated by Django 3.2 on 2023-08-17 10:47

import django.core.validators
from django.db import migrations, models
import documents.validators


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_template_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name_in_document',
            field=models.CharField(help_text="name in document, must have prefix '{{'and postfix '}}'", max_length=70, unique=True, validators=[documents.validators.NameInDocumentRegexValidator(), django.core.validators.MinLengthValidator(7)], verbose_name='template name in document'),
        ),
    ]
