# Generated by Django 3.2 on 2023-07-23 09:31

import core.utils.make_document_directory_path
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0009_alter_template_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(150)])),
                ('description', models.TextField(blank=True, max_length=500, unique=True)),
                ('file', models.FileField(upload_to=core.utils.make_document_directory_path.make_documents_directory_path)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date of publication')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='author_title_unique'),
        ),
    ]
