# Generated by Django 3.2 on 2023-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_template_name_in_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentspackage',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='description'),
        ),
    ]
