# Generated by Django 3.2 on 2023-08-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_documentspackage_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordtemplatevalue',
            options={'verbose_name': 'RecordTemplateValue', 'verbose_name_plural': 'RecordTemplateValue'},
        ),
    ]
