# Generated by Django 3.2 on 2023-07-25 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0010_auto_20230723_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTemplateDefaultValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=300)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertemplatedefaultvalue', to='documents.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertemplatedefaultvalue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DefaultUserTemplateValue',
                'verbose_name_plural': 'DeafaultUserTemplateValues',
            },
        ),
        migrations.DeleteModel(
            name='DefaultUserTemplateValue',
        ),
        migrations.AddConstraint(
            model_name='usertemplatedefaultvalue',
            constraint=models.UniqueConstraint(fields=('user', 'template'), name='default_user_template_unique'),
        ),
    ]
