# Generated by Django 3.2 on 2023-08-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_recordtemplatevalue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['creation_date'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
    ]
