# Generated by Django 3.2 on 2023-07-25 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20230725_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='document',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of creation'),
            preserve_default=False,
        ),
    ]
