# Generated by Django 3.2 on 2023-07-26 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20230726_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdocumentpackage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
