# Generated by Django 3.2 on 2023-08-17 10:00

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230804_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[users.validators.CustomUnicodeUsernameValidator(), django.core.validators.MinLengthValidator(4)], verbose_name='username'),
        ),
    ]
